### ISSUE TITLE
Does not work with Python 2.7

### ISSUE THREAD

**Issue by alanjds** [Taywee/rabbitadmin#1]
Hi.

The actual state does not work with Python 2.7. There are issues with import paths and the use of ``str('foo', 'utf-8')`` not supported on Py27.

I can manage to fix this via `futures` from [python-future.org](http://python-future.org/compatible_idioms.html), but I guess that is better to ask if this is desirable, to not waste people time (mine included).

Can you please inform your impressions about this?

Thanks.

**Comment by Taywee** [comment]
These are good points, but this is technically not the first the place to fix this, as this module is generated by (makerestapiclient)[https://github.com/Taywee/makerestapiclient], and the http client is cloned from there as well, though it looks like it's probably just the http client module that needs fixing.

**Comment by Taywee** [comment]
Don't worry about these changes, I'll make them in the right places.  Thanks for the issue.

**Comment by Taywee** [comment]
This should be working now, as of version 1.2.1, though I have switched from python's urllib to requests, as python's internal libs for version 2 don't allow PUT or DELETE in a way that is easily compatible with Python 3.  If you are watching for specific exceptions, make sure to watch for the requests versions instead now.
